# Site settings
title: Grupos Renacer en Costa Rica
email: eduardo.mena@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Los Grupos Renacer son Grupos de ayuda mutua entre “pares” para padres y madres que enfrentan la muerte de hijos
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://gruporenacercr.com" # the base hostname & protocol for your site

gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown

sass:
    style: compressed